version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: jogo_da_velha_postgres_container
    environment:
      POSTGRES_DB: jvbd
      POSTGRES_USER: jvbd
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network
    restart: always

volumes:
  postgres_data:

networks:
  app-network:
